version: 2

build:
  os: ubuntu-22.04  # Use a more stable OS version
  tools:
    python: "3.10"  # Use Python 3.10 or 3.11 instead of 3.13

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt
