version: 2

build:
  os: ubuntu-22.04  # Use a stable OS version
  tools:
    python: "3.13"  # Use 3.10 since 3.13 is experimental

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
    - pip install sphinx-book-theme  # Ensure theme is installed
